language: java
jdk: oraclejdk11
script:
- mvn test
cache:
  directories:
  - target/lib
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - cat target/pmd.xml
branches:
  only:
  - master
