blank_issues_enabled: false
contact_links:
  - name: "SQLancer Community"
    url: "https://join.slack.com/t/sqlancer/shared_invite/zt-eozrcao4-ieG29w1LNaBDMF7OB_~ACg"
    about: "Please ask and answer questions here"