name: CI tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  misc:
    name: Misc tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: mvn -B package -DskipTests=true
      - name: Verify
        run: mvn -B verify -DskipTests=true
      - name: Misc Tests
        run: mvn -B '-Dtest=!sqlancer.dbms.**' test
